Add mdakits logos
MDAnalysis/branding pull request #7
Opened 2024-06-22 06:30 UTC by lilyminium

This PR adds logos for
* the MDAKits registry
* Downstream MDAKits

These are licensed differently. However I didn't take on #6, as I'm not fully certain how transferring the trademark to NF affects the licensed.

Note: the original 'Atom' logo doesn't allow derivatives to be distributed. I think the MDAKits registry logo would be a derivative. Just checking this isn't problematic in any way?

2024-06-22 14:32 UTC, orbeckst requested changes
Thanks for updating branding, too, only saw this after reviewing on MDAKits. Sorry for brevity… reviewing from mobile. 

Can we keep logos and templates separate, ie make a top-level templates dir and then add there mdakits with empty gears. That should make the licensing clearer. Otherwise we have files with different licenses/restrictions next to each other.

2024-06-23 17:15 UTC, lilyminium commented
Thanks @orbeckst -- done, although also happy to make a new templates repository if that would be easiest!

2024-06-23 18:42 UTC, orbeckst approved these changes

2024-07-04 00:30 UTC, merged

2024-07-04 00:31 UTC, orbeckst commented
Sorry @lilyminium , I hadn't realized that we hadn't merged your additions.